apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency-chart.fullname" . }}
spec:
  selector:
    {{- include "muffin-currency-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
